version: '2'
services:
  # appium with android emulator
  appemulator:

    container_name: emulator

    image: rgonalo/appium-emulator

    expose:
      - 4723

  app:

    build: .

    depends_on:
      - appemulator

    environment:
      - REMURL:'http://appemulator:4723/wd/hub'
      - USRS:${ULIST}
      - PWS:${PLIST}

    container_name: app

    ports:
      - "4723:4723"

    # make sure emulator linked
    command: ping -c 1 appemulator
    command: ls /data
    # example
    # command: xvfb-run pybot -v REMOTE_URL:'${REMURL}' -v BROWSER:firefox -v login:${USRS[0]} -v password:${PWS[0]} -v to:10 -d outputs -t '*Android*' bing.txt.robot

    # below for debugging
    # command: sh

    links:
      - appemulator