version: 2
# per: https://circleci.com/docs/2.0/sample-config/#nav-button
jobs:
  build:
    working_directory: ~/standalone
    docker:
      - image: docker:17.03-git
      # multiple containers not working for beta
      #- image: bash:4.4
    steps:
      - checkout
      - setup_remote_docker    
      - run:
          name: Build container
          command: docker build -t kenney/mobile .
      - run: |
          apk add --no-cache --update openssl bash
          openssl aes-256-cbc -d -in secret-env-cipher -k "${KEY}" >> ~/.circlerc
      - run: |
          bash << EOF
          #!/bin/bash
          . ~/.circlerc
          for i in `seq 1 2`; do docker run -v "${PWD}":/data -t kenney/mobile -i NONBLOCK -v BROWSER:firefox -v login:${SBLIST[${i}]} -v password:${SBPLIST[${i}]} -v to:10 -v pVersion:8.1 -t "Fullfill All" -d outputs bing.txt.robot || true; done
          EOF

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
