version: 2
# per: https://circleci.com/docs/2.0/sample-config/#nav-button
jobs:
  build:
    working_directory: ~/standalone
    docker:
      - image: docker:17.03-git
    steps:
      - checkout
      - setup_remote_docker    
      - run:
          name: Build container
          command: docker build -t kenney/mobile .
          
  unittest:
    working_directory: ~/standalone
    docker:
      - image: docker:17.03-dind
    steps:
      - checkout
      - setup_remote_docker
      - run: docker version
      # multiple images for connecting ports of swarms of selenium grid, appium, others can be done...
      # https://circleci.com/docs/2.0/executor-types/
      # below is only because of private docker
      - run: docker build -t kenney/mobile .
      - run: docker images
          
  buildswarm:
    working_directory: ~/swarm
    docker:
      - image: docker:17.03-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container
          command: docker build -t kenney/mobile:swarm .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - buildswarm
      - unittest:
          requires:
            - build
