version: 2
# per: https://circleci.com/docs/2.0/sample-config/#nav-button
jobs:
  build:
    working_directory: ~/standalone
    docker:
      - image: kenney/robot-firefox-alpine
    steps:
      - checkout
      - run: curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
      - run: docker build -t kenney/mobile . 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
