version: 2
# per: https://circleci.com/docs/2.0/sample-config/#nav-button
jobs:
  build:
    working_directory: ~/standalone
    docker:
      - image: kenney/robot-firefox
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install tar
          command: yum install -y tar
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.06.0-ce-rc2"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin                
      - run:
          name: Build service
          command: make

  buildswarm:
    working_directory: ~/swarm
    docker:
      - image: kenney/robot-firefox-swarm
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install tar
          command: yum install -y tar
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.06.0-ce-rc2"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin                  
      - run:
          name: Build service
          command: make
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - buildswarm
