version: 2
# per: https://circleci.com/docs/2.0/sample-config/#nav-button
jobs:
  build:
    working_directory: ~/standalone
    docker:
      - image: kenney/robot-firefox
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            wget -qO- https://get.docker.com/ | sh            
      - run:
          name: Build container
          command: docker build -t kenney/mobile . || true
          
  buildswarm:
    working_directory: ~/swarm
    docker:
      - image: kenney/robot-firefox-swarm
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            wget -qO- https://get.docker.com/ | sh  
      - run:
          name: Build container
          command: docker build -t kenney/mobile:swarm . || true
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - buildswarm
