version: '2'
services:
  # chrome driver with xvfb
  chrome-xvfb:
    image: markadams/chromium-xvfb

  # appium with android emulator
  appium-emulator:
    image: rgonalo/appium-emulator

  #robotframework:
  #  image: kenney/robot-firefox-centos

  # robotframework code
  mobile:
    image: kenney/mobile

  # config packages, data only container
  configpackage:
    image: heinvestmentsllc/private

  unittest:
    build: .
    depends_on:
     - chrome-xvfb
     - appium-emulator
     - configpackage
     - mobile

    ports:
     - "4723:4723"
